In [2]:
import numpy as np #linspace預設num=50，會列出50個
np.linspace(-3,3)

array([-3.        , -2.87755102, -2.75510204, -2.63265306, -2.51020408,
       -2.3877551 , -2.26530612, -2.14285714, -2.02040816, -1.89795918,
       -1.7755102 , -1.65306122, -1.53061224, -1.40816327, -1.28571429,
       -1.16326531, -1.04081633, -0.91836735, -0.79591837, -0.67346939,
       -0.55102041, -0.42857143, -0.30612245, -0.18367347, -0.06122449,
        0.06122449,  0.18367347,  0.30612245,  0.42857143,  0.55102041,
        0.67346939,  0.79591837,  0.91836735,  1.04081633,  1.16326531,
        1.28571429,  1.40816327,  1.53061224,  1.65306122,  1.7755102 ,
        1.89795918,  2.02040816,  2.14285714,  2.26530612,  2.3877551 ,
        2.51020408,  2.63265306,  2.75510204,  2.87755102,  3.        ])

In [5]:
import numpy as np #linspace預設num=50，會列出50個
np.linspace(-3,3,num=100)
array=np.linspace(-3,3,num=100)
array*10 #可以做陣列運算

array([-30.        , -29.39393939, -28.78787879, -28.18181818,
       -27.57575758, -26.96969697, -26.36363636, -25.75757576,
       -25.15151515, -24.54545455, -23.93939394, -23.33333333,
       -22.72727273, -22.12121212, -21.51515152, -20.90909091,
       -20.3030303 , -19.6969697 , -19.09090909, -18.48484848,
       -17.87878788, -17.27272727, -16.66666667, -16.06060606,
       -15.45454545, -14.84848485, -14.24242424, -13.63636364,
       -13.03030303, -12.42424242, -11.81818182, -11.21212121,
       -10.60606061, -10.        ,  -9.39393939,  -8.78787879,
        -8.18181818,  -7.57575758,  -6.96969697,  -6.36363636,
        -5.75757576,  -5.15151515,  -4.54545455,  -3.93939394,
        -3.33333333,  -2.72727273,  -2.12121212,  -1.51515152,
        -0.90909091,  -0.3030303 ,   0.3030303 ,   0.90909091,
         1.51515152,   2.12121212,   2.72727273,   3.33333333,
         3.93939394,   4.54545455,   5.15151515,   5.75757576,
         6.36363636,   6.96969697,   7.57575758,   8.18

In [27]:
np.random.randint(50,high=101,size=100) #不包含101，建立100個50-100間的數 ，一維資料

array([98, 66, 98, 62, 62, 95, 50, 52, 99, 90, 67, 74, 84, 89, 98, 52, 76,
       95, 72, 95, 83, 88, 54, 70, 63, 97, 88, 83, 70, 59, 93, 86, 94, 97,
       78, 68, 55, 61, 99, 53, 54, 55, 71, 97, 75, 75, 95, 92, 88, 69, 95,
       78, 88, 57, 70, 69, 97, 55, 56, 98, 60, 53, 97, 77, 82, 87, 88, 64,
       51, 74, 72, 62, 98, 87, 80, 90, 88, 57, 89, 71, 95, 53, 87, 64, 70,
       87, 58, 73, 59, 58, 91, 54, 64, 99, 51, 62, 86, 91, 97, 87])

In [28]:
np.random.randint(50,high=101,size=(50,5))  #建立二維資料 50列、5欄

array([[ 75,  50,  81,  72, 100],
       [ 99,  58,  71,  63,  89],
       [ 67,  89,  82,  91,  75],
       [ 97,  57,  81,  71,  97],
       [ 86,  93,  69,  65,  70],
       [ 75,  67,  57,  96,  90],
       [ 74,  59,  87,  56,  75],
       [ 82,  63,  52,  79,  62],
       [ 81,  77,  55,  91,  74],
       [ 80,  88,  75,  58,  54],
       [100,  98,  93,  63,  68],
       [ 64,  81,  94,  89,  69],
       [ 88,  54,  80,  75,  80],
       [ 79,  98,  89, 100, 100],
       [ 55,  51,  75,  68,  64],
       [ 56,  73,  57,  96,  50],
       [ 53,  57,  55,  71,  61],
       [ 69,  93,  82, 100,  59],
       [ 89,  74,  70,  74,  85],
       [ 71,  99,  74,  72,  69],
       [ 65,  60,  52,  73,  95],
       [ 79,  79,  75,  74,  51],
       [ 97,  97,  54,  61,  83],
       [ 92,  89,  91,  71,  62],
       [ 78,  97,  68,  93,  88],
       [ 81,  98,  59,  76,  67],
       [ 66,  71,  68,  53,  56],
       [ 73,  99,  73,  68,  50],
       [ 93,  75,  75,  70,  91],
       [ 59,  