In [2]:
import numpy as np #linspace預設num=50，會列出50個
np.linspace(-3,3)

array([-3.        , -2.87755102, -2.75510204, -2.63265306, -2.51020408,
       -2.3877551 , -2.26530612, -2.14285714, -2.02040816, -1.89795918,
       -1.7755102 , -1.65306122, -1.53061224, -1.40816327, -1.28571429,
       -1.16326531, -1.04081633, -0.91836735, -0.79591837, -0.67346939,
       -0.55102041, -0.42857143, -0.30612245, -0.18367347, -0.06122449,
        0.06122449,  0.18367347,  0.30612245,  0.42857143,  0.55102041,
        0.67346939,  0.79591837,  0.91836735,  1.04081633,  1.16326531,
        1.28571429,  1.40816327,  1.53061224,  1.65306122,  1.7755102 ,
        1.89795918,  2.02040816,  2.14285714,  2.26530612,  2.3877551 ,
        2.51020408,  2.63265306,  2.75510204,  2.87755102,  3.        ])

In [5]:
import numpy as np #linspace預設num=50，會列出50個
np.linspace(-3,3,num=100)
array=np.linspace(-3,3,num=100)
array*10 #可以做陣列運算

array([-30.        , -29.39393939, -28.78787879, -28.18181818,
       -27.57575758, -26.96969697, -26.36363636, -25.75757576,
       -25.15151515, -24.54545455, -23.93939394, -23.33333333,
       -22.72727273, -22.12121212, -21.51515152, -20.90909091,
       -20.3030303 , -19.6969697 , -19.09090909, -18.48484848,
       -17.87878788, -17.27272727, -16.66666667, -16.06060606,
       -15.45454545, -14.84848485, -14.24242424, -13.63636364,
       -13.03030303, -12.42424242, -11.81818182, -11.21212121,
       -10.60606061, -10.        ,  -9.39393939,  -8.78787879,
        -8.18181818,  -7.57575758,  -6.96969697,  -6.36363636,
        -5.75757576,  -5.15151515,  -4.54545455,  -3.93939394,
        -3.33333333,  -2.72727273,  -2.12121212,  -1.51515152,
        -0.90909091,  -0.3030303 ,   0.3030303 ,   0.90909091,
         1.51515152,   2.12121212,   2.72727273,   3.33333333,
         3.93939394,   4.54545455,   5.15151515,   5.75757576,
         6.36363636,   6.96969697,   7.57575758,   8.18

In [27]:
np.random.randint(50,high=101,size=100) #不包含101，建立100個50-100間的數 ，一維資料

array([98, 66, 98, 62, 62, 95, 50, 52, 99, 90, 67, 74, 84, 89, 98, 52, 76,
       95, 72, 95, 83, 88, 54, 70, 63, 97, 88, 83, 70, 59, 93, 86, 94, 97,
       78, 68, 55, 61, 99, 53, 54, 55, 71, 97, 75, 75, 95, 92, 88, 69, 95,
       78, 88, 57, 70, 69, 97, 55, 56, 98, 60, 53, 97, 77, 82, 87, 88, 64,
       51, 74, 72, 62, 98, 87, 80, 90, 88, 57, 89, 71, 95, 53, 87, 64, 70,
       87, 58, 73, 59, 58, 91, 54, 64, 99, 51, 62, 86, 91, 97, 87])

In [44]:
np.random.randint(50,high=101,size=(50,5))  #建立二維資料 50列、5欄

array([[ 74,  74,  77,  87,  95],
       [ 92,  50,  97, 100,  77],
       [ 88,  89,  99,  73,  71],
       [ 79,  90,  51,  95,  71],
       [ 92,  64,  90,  66,  70],
       [ 76,  65,  87,  71,  59],
       [ 51,  75,  67,  76,  94],
       [ 86,  62,  61,  98,  66],
       [ 99,  92,  82,  91,  98],
       [ 86,  98,  50,  50,  64],
       [ 51,  57,  82,  64,  66],
       [ 53,  75,  54,  52,  76],
       [ 61,  53,  61,  89,  99],
       [ 87,  56,  64,  55,  56],
       [ 79,  68,  59,  57,  53],
       [ 72,  59,  76,  56,  75],
       [ 96,  76,  68,  94,  70],
       [ 50,  90,  74,  83,  66],
       [ 60,  58,  80,  83,  72],
       [ 69,  64,  86,  83,  85],
       [ 66,  50,  55,  98,  71],
       [ 99,  92,  89,  96,  87],
       [ 53,  56,  95,  55,  60],
       [ 55,  56,  91,  73,  62],
       [ 71,  61,  63,  80,  96],
       [ 50,  64,  54,  79,  88],
       [ 96,  70,  76,  76,  93],
       [ 86,  88,  61,  55,  89],
       [ 53,  77,  96,  94,  57],
       [ 74,  

In [51]:
content=np.random.randint(50,high=101,size=(50,5))

In [57]:
import pandas as pd
pd.DataFrame(data=content,index=range(1,51),columns=['國文','數學','英文','社會','自然'])
df1=pd.DataFrame(data=content,index=range(1,51),columns=['國文','數學','英文','社會','自然'])
df1

國文   數學  英文   社會   自然
1    79   72  50   73  100
2   100   99  58   80   84
3    73   80  84   91   77
4    85   97  69   70   97
5    93   90  94   86   97
6    64   55  89   58   68
7    77   80  50   69   71
8    78   90  64   52   62
9    55   99  83   87   92
10   99   54  76   83   78
11   87   95  99   95  100
12   94   56  64   65   82
13   69   79  58   67   71
14   73   92  71   52   56
15   85   77  78   75   69
16   99   71  71   87   75
17   63   92  59   95   65
18   92   97  75   69   52
19   85   83  77   74   64
20   76   68  96   75   91
21   95   65  69   72   89
22   61   78  56   66   68
23   81   87  71   70   64
24   94   91  91   66   60
25   86   96  56   62   99
26   68   83  64   51   88
27   83   82  53   85   72
28   54   53  63   60   51
29   99   57  82  100   63
30   57  100  51   95   52
31   93   93  91   57   78
32   91   54  65   86   72
33   78   80  84   57   95
34   69   96  74   53   91
35   50   85  87   70   73
36   60   95  93   62   98
37   52   62  59   88   61
38   56   91  86   77   70
39   63   79  79   80   84
40   89   78  69   61   56
41  100   81  57   90   69
42   95   87  75   57   72
43   77   93  64   93   75
44   78   87  59   75   67
45   94   86  62   65   94
46   86   84  72   85   58
47   58   92  60   68   61
48   51   66  83  100   88
49   57   88  70   96   62
50   87   75  59   73   67

In [59]:
df1['國文']+df1['英文']+df1['數學']+df1['社會']+df1['自然']

1     374
2     421
3     405
4     418
5     460
6     334
7     347
8     346
9     416
10    390
11    476
12    361
13    344
14    344
15    384
16    403
17    374
18    385
19    383
20    406
21    390
22    329
23    373
24    402
25    399
26    354
27    375
28    281
29    401
30    355
31    412
32    368
33    394
34    383
35    365
36    408
37    322
38    380
39    385
40    353
41    397
42    386
43    402
44    366
45    401
46    385
47    339
48    388
49    373
50    361
dtype: int64

In [66]:
content=np.random.randint(50,high=101,size=(50,5))

In [68]:
import pandas as pd
pd.DataFrame(data=content, index=[f"第{i}號"for i in range(1,51)],columns=['國文','數學','英文','社會','自然'])
df1=pd.DataFrame(data=content, index=[f"第{i}號"for i in range(1,51)],columns=['國文','數學','英文','社會','自然'])
df1

國文   數學   英文  社會  自然
第1號    59   75   92  86  76
第2號    85   54   84  80  77
第3號    89   69   72  66  59
第4號   100   53   78  52  78
第5號    68   91   82  53  53
第6號    74   76   73  62  79
第7號    86   51   82  77  62
第8號    72   71   58  59  82
第9號    51   93   85  75  56
第10號   72   60  100  64  77
第11號   60   91   52  76  51
第12號   54   52   92  84  60
第13號   69   93   52  51  71
第14號   71   73   69  62  82
第15號   99   58   81  61  52
第16號   51   81   54  68  81
第17號  100   81   72  60  72
第18號   60   88   86  75  84
第19號   99   78   92  53  84
第20號   93   56  100  95  70
第21號   74   98   61  90  50
第22號   79   78   71  88  76
第23號   91   51   85  65  65
第24號   69   56   97  62  55
第25號   96   72   82  68  68
第26號   97   71   57  85  62
第27號   71   94   65  57  64
第28號   83   71   83  54  74
第29號   84   89   90  50  88
第30號   85   96   63  82  85
第31號   89   84   58  80  51
第32號   67   97   69  88  86
第33號   85   72   77  93  79
第34號   50   91   76  79  54
第35號   96   61   99  75  79
第36號   90   64   52  70  87
第37號   92   51   60  64  57
第38號   78   63   85  81  84
第39號   96   99   78  97  74
第40號   65   61   53  95  53
第41號   50   96   64  64  89
第42號   57   88   87  53  88
第43號   90   99   59  60  68
第44號   73   52   59  60  53
第45號   67   80   70  96  76
第46號   94   93   65  76  66
第47號   50   61   67  83  95
第48號   77  100   99  93  54
第49號   70   82   87  90  82
第50號   77  100   96  55  94

In [69]:
df1.loc["第1號"] #dataFrame.loc[key,欄] 使用key

國文    59
數學    75
英文    92
社會    86
自然    76
Name: 第1號, dtype: int64

In [70]:
df1.loc[["第1號","第5號","第10號"]]

國文  數學   英文  社會  自然
第1號   59  75   92  86  76
第5號   68  91   82  53  53
第10號  72  60  100  64  77

In [71]:
df1.iloc[:5] #dataFrame.loc[列,欄] 使用index

國文  數學  英文  社會  自然
第1號   59  75  92  86  76
第2號   85  54  84  80  77
第3號   89  69  72  66  59
第4號  100  53  78  52  78
第5號   68  91  82  53  53

In [72]:

df1.iloc[-5:]

國文   數學  英文  社會  自然
第46號  94   93  65  76  66
第47號  50   61  67  83  95
第48號  77  100  99  93  54
第49號  70   82  87  90  82
第50號  77  100  96  55  94

In [73]:
df1.loc['第10號':'第15號']

國文  數學   英文  社會  自然
第10號  72  60  100  64  77
第11號  60  91   52  76  51
第12號  54  52   92  84  60
第13號  69  93   52  51  71
第14號  71  73   69  62  82
第15號  99  58   81  61  52